-- IDENTITY columns
-- generated always <-> values always get produced by DB2 (guarantees UK)
-- generated by default <-> values can be set from the user but if such aren't provided DB2 will assign some (no UK guarantee)

-- generate always as identity (start with <n>, increment by <m>) example
create table subscriber
(
    subscriberId integer generated always as
        identity (start with 100, increment by 100),
    firstname varchar(100),
    lastname varchar(100)
);

-- generated by default as identity (start with <n>, increment by <m>) example
create table movie
(
    id integer generated by default as identity
    (start with 100, increment by 100),
    title varchar(50) not null,
    year integer not null
);

-- SEQUENCE objects
-- unique value generation mechanism with db-level scope
create table t1(salary int);

create sequence myseq
    start with 10
    increment by 1
    no cycle;

insert into t1 values (nextval for myseq);
insert into t1 values (nextval for myseq);
insert into t1 values (nextval for myseq);

select * from t1;

-- prevval <-> current value of SEQUENCE object
select prevval for myseq from sysibm.SYSDUMMY1

-- nextval <-> next value of sequence object

-- Tables from the system catalog
-- SYSIBM <-> tables optimized for use in DB2 (schema)
-- SYSCAT <-> views of the tables in SYSIBM (schema)
-- SYSSTAT <-> stats about the database (schema)

-- examples of views in the system catalog
-- syscat.tables
-- syscat.indexes
-- syscat.columns
-- syscat.functions
-- syscat.producers